team_names_parsed_link_3 = dict()

team_names_parsed_link_3['CSKA Moscow'] = '[CSK](https://www.euroleague.net/competition/teams/showteam?clubcode=CSK&seasoncode=E2019)'
team_names_parsed_link_3['Fenerbahce Beko Istanbul'] = '[FNB](https://www.euroleague.net/competition/teams/showteam?clubcode=ULK&seasoncode=E2019)'
team_names_parsed_link_3['Anadolu Efes Istanbul'] = '[EFS](https://www.euroleague.net/competition/teams/showteam?clubcode=IST&seasoncode=E2019)'
team_names_parsed_link_3['FC Bayern Munich'] = '[BAY](https://www.euroleague.net/competition/teams/showteam?clubcode=MUN&seasoncode=E2019)'
team_names_parsed_link_3['FC Barcelona'] = '[BAR](https://www.euroleague.net/competition/teams/showteam?clubcode=BAR&seasoncode=E2019)'
team_names_parsed_link_3['Olympiacos Piraeus'] = '[OLY](https://www.euroleague.net/competition/teams/showteam?clubcode=OLY&seasoncode=E2019)'
team_names_parsed_link_3['Khimki Moscow Region'] = '[KHI](https://www.euroleague.net/competition/teams/showteam?clubcode=KHI&seasoncode=E2019)'
team_names_parsed_link_3['Maccabi FOX Tel Aviv'] = '[MTA](https://www.euroleague.net/competition/teams/showteam?clubcode=TEL&seasoncode=E2019)'
team_names_parsed_link_3['Zalgiris Kaunas'] = '[ZAL](https://www.euroleague.net/competition/teams/showteam?clubcode=ZAL&seasoncode=E2019)'
team_names_parsed_link_3['KIROLBET Baskonia Vitoria-Gasteiz'] = '[KBA](https://www.euroleague.net/competition/teams/showteam?clubcode=BAS&seasoncode=E2019)'
team_names_parsed_link_3['Real Madrid'] = '[RMA](https://www.euroleague.net/competition/teams/showteam?clubcode=MAD&seasoncode=E2019)'
team_names_parsed_link_3['AX Armani Exchange Milan'] = '[MIL](https://www.euroleague.net/competition/teams/showteam?clubcode=MIL&seasoncode=E2019)'
team_names_parsed_link_3['Panathinaikos OPAP Athens'] = '[PAO](https://www.euroleague.net/competition/teams/showteam?clubcode=PAN&seasoncode=E2019)'
team_names_parsed_link_3['LDLC ASVEL Villeurbanne'] = '[ASV](https://www.euroleague.net/competition/teams/showteam?clubcode=ASV&seasoncode=E2019)'
team_names_parsed_link_3['ALBA Berlin'] = '[BER](https://www.euroleague.net/competition/teams/showteam?clubcode=BER&seasoncode=E2019)'
team_names_parsed_link_3['Valencia Basket'] = '[VBC](https://www.euroleague.net/competition/teams/showteam?clubcode=PAM&seasoncode=E2019)'
team_names_parsed_link_3['Crvena Zvezda mts Belgrade'] = '[CZV](https://www.euroleague.net/competition/teams/showteam?clubcode=RED&seasoncode=E2019)'
team_names_parsed_link_3['Zenit St Petersburg'] = '[ZEN](https://www.euroleague.net/competition/teams/showteam?clubcode=DYR&seasoncode=E2019)'

team_names_parsed_link_3['Tofas Bursa'] = '[TOF](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=BUR&seasoncode=U2019)'
team_names_parsed_link_3['Darussafaka Tekfen Istanbul'] = '[DTI](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=DAR&seasoncode=U2019)'
team_names_parsed_link_3['Buducnost VOLI Podgorica'] = '[BUD](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=BUD&seasoncode=U2019)'
team_names_parsed_link_3['Promitheas Patras'] = '[PRO](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=PAT&seasoncode=U2019)'
team_names_parsed_link_3['AS Monaco'] = '[MON](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=MCO&seasoncode=U2019)'
team_names_parsed_link_3['MoraBanc Andorra'] = '[MBA](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=ANR&seasoncode=U2019)'
team_names_parsed_link_3['ratiopharm Ulm'] = '[ULM](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=ULM&seasoncode=U2019)'
team_names_parsed_link_3['Segafredo Virtus Bologna'] = '[VIR](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=VIR&seasoncode=U2019)'
team_names_parsed_link_3['Maccabi Rishon LeZion'] = '[RLZ](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=RIS&seasoncode=U2019)'
team_names_parsed_link_3['Partizan NIS Belgrade'] = '[PAR](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=PAR&seasoncode=U2019)'
team_names_parsed_link_3['Lokomotiv Kuban Krasnodar'] = '[LOK](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=TIV&seasoncode=U2019)'
team_names_parsed_link_3['Umana Reyer Venice'] = '[URV](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=VNC&seasoncode=U2019)'
team_names_parsed_link_3['Limoges CSP'] = '[CSP](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=LMG&seasoncode=U2019)'
team_names_parsed_link_3['Rytas Vilnius'] = '[RYT](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=LIE&seasoncode=U2019)'
team_names_parsed_link_3['Nanterre 92'] = '[NTR](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=NTR&seasoncode=U2019)'
team_names_parsed_link_3['Joventut Badalona'] = '[CJB](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=JOV&seasoncode=U2019)'
team_names_parsed_link_3['Germani Brescia Leonessa'] = '[BRE](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=BRE&seasoncode=U2019)'
team_names_parsed_link_3['UNICS Kazan'] = '[UNK](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=UNK&seasoncode=U2019)'
team_names_parsed_link_3['Cedevita Olimpija Ljubljana'] = '[COL](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=LJU&seasoncode=U2019)'
team_names_parsed_link_3['Galatasaray Doga Sigorta Istanbul'] = '[GAL](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=GAL&seasoncode=U2019)'
team_names_parsed_link_3['EWE Baskets Oldenburg'] = '[EBO](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=OLD&seasoncode=U2019)'
team_names_parsed_link_3['Asseco Arka Gdynia'] = '[ARK](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=SOP&seasoncode=U2019)'
team_names_parsed_link_3['Unicaja Malaga'] = '[UNI](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=MAL&seasoncode=U2019)'
team_names_parsed_link_3['Dolomiti Energia Trento'] = '[TRE](https://www.eurocupbasketball.com/eurocup/competition/teams/showteam?clubcode=TRN&seasoncode=U2019)'
